CKPT_DIR: "../artifacts/ckpts"
LOG_DIR: "../artifacts/logs"
IMG_OUT_DIR: "../artifacts/img"
MODEL:
  img_size: [480, 640, 3]
  patch_size: 16
  embed_size: 32
  num_encoder_blocks: 4
  reassamble_embed_size: 64
  scales: [4, 8, 16, 32]
DATA:
  batch_size: 2
  root: "../data"
OPTIM:
  optimizer: "AdamW"
  lr: 0.0005
  num_epochs: 100000
  eval_every: 5
