CKPT_DIR: "../artifacts/ckpts"
LOG_DIR: "../artifacts/logs"
IMG_OUT_DIR: "../artifacts/img"
MODEL:
  img_size: [384, 384, 3]
  patch_size: 16
  embed_size: 128
  num_encoder_blocks: 12
  reassamble_embed_size: 256
  scales: [4, 8, 16, 32]
  blocks_ids: [2, 5, 8, 11]
DATA:
  batch_size: 2
  root: "../data"
OPTIM:
  optimizer: "AdamW"
  lr: 0.0001
  num_epochs: 100000
  eval_every: 5
  gradient_clip: true
  scheduler: ""
  T_max: 100
  eta_min: 0.000001
