CKPT_DIR: "../artifacts/ckpts"
LOG_DIR: "../artifacts/logs"
IMG_OUT_DIR: "../artifacts/img"
MODEL:
  task: "depth_est"
  img_size: [384, 384, 3]
  num_outputs: 1
  patch_size: 16
  embed_size: 128
  num_encoder_blocks: 6
  reassamble_embed_size: 256
  scales: [8, 16]
  blocks_ids: [4, 5]
  num_heads: 8
DATA:
  dataset: "NYUDepthDataset"
  batch_size: 2
  root: "../data"
OPTIM:
  loss: "AffineInvariantDepthLoss"
  optimizer: "AdamW"
  lr: 0.0001
  num_epochs: 100000
  eval_every: 5
  gradient_clip: true
  scheduler: ""
  T_max: 100
  eta_min: 0.000001
