CKPT_DIR: "../artifacts/ckpts"
LOG_DIR: "../artifacts/logs"
IMG_OUT_DIR: "../artifacts/img"
MODEL:
  model_name: "DPT_pretrained"
  task: "depth_est"
  img_size: [224, 224, 3]
  patch_size: 16
  embed_size: 768
  num_encoder_blocks: 12
  scales: [4, 8, 16, 32]
  blocks_ids: [8, 9, 10, 11]
  reassamble_embed_size: 256
  num_outputs: 1
  trainable_encoder: true
DATA:
  dataset: "NYUDepthDataset"
  batch_size: 2
  root: "../data"
OPTIM:
  loss: "AffineInvariantDepthLoss"
  optimizer: "AdamW"
  lr: 0.0001
  num_epochs: 100000
  eval_every: 1
  gradient_clip: true
  scheduler: ""
  T_max: 100
  eta_min: 0.000001
