CKPT_DIR: "../artifacts/ckpts"
LOG_DIR: "../artifacts/logs"
IMG_OUT_DIR: "../artifacts/img"
MODEL:
  model_name: "DPT"
  task: "depth_est"
  img_size: [224, 224, 3]
  patch_size: 16
  embed_size: 128
  num_heads: 8
  num_encoder_blocks: 6
  scales: [8, 16]
  blocks_ids: [4, 5]
  reassamble_embed_size: 256
  num_outputs: 1
DATA:
  dataset: "NYUDepthDataset"
  batch_size: 2
  root: "../data"
OPTIM:
  loss: "AffineInvariantDepthLoss"
  optimizer: "AdamW"
  lr: 0.0001
  num_epochs: 100
  eval_every: 5
  gradient_clip: true
  scheduler: ""
  T_max: 100
  eta_min: 0.000001
